version: '3.8'

services:
  web:
    build: .
    command: python run.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:          # <-- Agrega esto para que Docker lea tu archivo .env
      - .env           # <-- 
    environment:
      - PYTHONUNBUFFERED=1
      - USE_PROD_ENV=false
      - DATABASE_URL_DEV=postgresql://kiwi_user:kiwi_pass@db:5432/kiwi_db
      - JWT_ACCESS_TOKEN_EXPIRES_MINUTES=20160
      - JWT_REFRESH_TOKEN_EXPIRES_DAYS=7
      - JWT_SECRET_KEY=46971d87780983f4784cfc5999fba142b0e136b04899e08ec58d06840344f65b
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: kiwi_user
      POSTGRES_PASSWORD: kiwi_pass
      POSTGRES_DB: kiwi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: