"""Add decisiones_profes and comentarios_caso

Revision ID: 460d657e178f
Revises: f2a3b4c5d6e7
Create Date: 2026-05-28 13:29:00.126667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460d657e178f'
down_revision = 'f2a3b4c5d6e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decisiones_profes', sa.JSON(), nullable=True))

    with op.batch_alter_table('caso_sancionado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comentarios_caso', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caso_sancionado', schema=None) as batch_op:
        batch_op.drop_column('comentarios_caso')

    with op.batch_alter_table('caso', schema=None) as batch_op:
        batch_op.drop_column('decisiones_profes')

    # ### end Alembic commands ###
