"""ajustes en models

Revision ID: 785915a11ad4
Revises: 85ac37daac05
Create Date: 2026-04-09 23:12:19.671718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785915a11ad4'
down_revision = '85ac37daac05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_sanciones', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estudiante', schema=None) as batch_op:
        batch_op.drop_column('num_sanciones')

    # ### end Alembic commands ###
