"""ajustes en modelos

Revision ID: 85ac37daac05
Revises: e1a2b3c4d5e6
Create Date: 2026-03-30 19:25:02.310761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ac37daac05'
down_revision = 'e1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caso_sancionado',
    sa.Column('sancion_id', sa.Integer(), nullable=False),
    sa.Column('caso_id', sa.Integer(), nullable=False),
    sa.Column('estudiantes_involucrados', sa.JSON(), nullable=False),
    sa.Column('descripcion_sancion', sa.String(length=200), nullable=False),
    sa.Column('fecha_sancion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['caso_id'], ['caso.caso_id'], ),
    sa.PrimaryKeyConstraint('sancion_id')
    )
    with op.batch_alter_table('caso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comentarios_profes', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caso', schema=None) as batch_op:
        batch_op.drop_column('comentarios_profes')

    op.drop_table('caso_sancionado')
    # ### end Alembic commands ###
