"""cambios en models

Revision ID: d4059e76e6da
Revises: 001_initial_baseline
Create Date: 2026-03-09 13:43:29.191242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4059e76e6da'
down_revision = '001_initial_baseline'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sancion', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('caso_metadata', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('evaluacion_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'evaluacion', ['evaluacion_id'], ['evaluacion_id'])
        batch_op.drop_column('estado')

    with op.batch_alter_table('evaluacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    with op.batch_alter_table('reporte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reporte', schema=None) as batch_op:
        batch_op.drop_column('activo')

    with op.batch_alter_table('evaluacion', schema=None) as batch_op:
        batch_op.drop_column('activo')

    with op.batch_alter_table('caso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('evaluacion_id')
        batch_op.drop_column('caso_metadata')
        batch_op.drop_column('sancion')
        batch_op.drop_column('closed')

    # ### end Alembic commands ###
