"""cambio modelo estudiante

Revision ID: e0f5d05ea673
Revises: f1f2f3f4f5f6
Create Date: 2026-05-21 02:18:32.422244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0f5d05ea673'
down_revision = 'f1f2f3f4f5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permisos__aplicacion',
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('permiso_id'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permisos__aplicacion')
    # ### end Alembic commands ###
